"""empty message

Revision ID: 0a293b0b425c
Revises: 0cc30da412e4
Create Date: 2024-03-25 23:47:36.614070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a293b0b425c'
down_revision = '0cc30da412e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
