"""empty message

Revision ID: 0cc30da412e4
Revises: 3e39995cdce0
Create Date: 2024-03-25 23:45:20.241713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc30da412e4'
down_revision = '3e39995cdce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comments_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
